### ISSUE TITLE
Crashes on start for 1.17.1

### ISSUE THREAD

**Issue by TheDraconicAge** [Visnaa/MoreJewels#1]
More Jewels (morejewels) encountered an error during the common_setup event phase
net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindFieldException

**Comment by Visnaa** [comment]
Hello TheDraconicAge,

Thanks for reporting a bug, I tested the new version of More Jewels with fixed world generation and it seems fine.
I would be very grateful if you test it and close the issue if the problem is fixed.

Regards, Visnaa
