### ISSUE TITLE
[enhancement] Clean Up the Data Folder

### ISSUE THREAD

**Issue by Dradon7** [Visnaa/MoreJewels#1]
Basically, there are a couple problems with your data folder.

The first issue with it is that you have too many crafting recipes. for most tools and helmets, you have 2 recipes, one for each orientation on the crafting table. But you make make 1 recipe that doesn't take up 9 slots instead of 2.
For example, if you wanted a helmet recipe, you would organize it like so:
"HHH"
"H  H"
What your doing it making two separate files with:
"       "      "HHH"
"HHH"      "H  H"
"H  H"      "       "

The trick is to remove any horizontal or vertical lines of air in the recipe.

The second issue is that you aren't using forge tags. This is just a good idea in general for mod compatability.

What you want to do is in your data folder, create a new folder called "forge." Then create a folder inside forge called "tags." Inside tags, create a folder called "items" and a folder called "blocks." Inside items create a folder called "gems," a folder called "ores", and then a json file called gems and a json file called ores.  Inside the gems folder, put a json file for each kind of gem (saphire, ruby, etc), and using the tag format, use your item ids ("morejewels:saphire"). After you did that for each gems, repeat it for ores inside the ores folder. Once thats done, go back to the json files called gems and ores, and for each gem, put the tag inside the json (not the id). That should look like "#forge:gems/saphire." Repeat inside the ores json. Then, you can exit the items folder, head over to the blocks folder, and go to the ores folder and ores json and put singular jsons with the item ids in the folder and put the tags in the ores json.

I know that I sound like a narcissistic asshole, I'm sorry. And if you already knew how do to that stuff also I'm sorry. And if that super confusing and not clear at all, there should be tutorials on youtube for adding forge tags to your items.

**Comment by Visnaa** [comment]
Thank you for reporting an issue!

I will add tags and better recipes in next version of modification. Soon you will see this changes.

**Comment by Visnaa** [comment]
Thank you for reporting an issue!
I will add tags and better recipes in next version of modification. Soon You will see this changes.

**Comment by Visnaa** [comment]
I added this enhancement in version 2.6
