### ISSUE TITLE
Eating anything gives me the "Something Between" achievement

### ISSUE THREAD

**Issue by FluffiKiki** [Visnaa/MoreJewels#3]
The achievement calls for eating a gemstone apple, but as soon as I eat any food item, it gives me the achievement. 
Currently using Forge 1.16.5, this happened on version 2.9. Thanks for any help!

Edit: Before I forget, screenshots. I'm currently in creative mode for this, but this happens in survival as well. These are food items that are eatable while in creative, and the only ones in my inventory. 
![2021-04-30 (1)](https://user-images.githubusercontent.com/42556991/116650938-c3f02700-a947-11eb-9997-3a7760f65d3d.png)
![2021-04-30](https://user-images.githubusercontent.com/42556991/116650939-c3f02700-a947-11eb-8efb-ec65c5a9adab.png)

**Comment by Visnaa** [comment]
Hello, thanks for reporting. I'm working on this, soon I will release fixed version.
