### ISSUE TITLE
Replace placeholders.

### ISSUE THREAD

**Issue by RDKRACZ** [Visnaa/MoreJewels#3]
MOD_ID for your own ID in main.class and modid.mixins.json.
This is crucial because when someone uses a few mods and Minecraft crashes then in the log he will see a meaningless "Mixin prepare failed preparing ExampleMixin in modid.mixins.json"

**Comment by Visnaa** [comment]
I hope [this](https://www.curseforge.com/minecraft/mc-mods/more-jewels/files/3158236) file will no longer crash your game.
