### ISSUE TITLE
Ore Texture Difficulties

### ISSUE THREAD

**Issue by TheDraconicAge** [Visnaa/MoreJewels#3]
Deepslate Onyx Ore looks very similar to Deepslate Coal Ore

**Comment by TheDraconicAge** [comment]
Still a problem.
![2021-08-21_17 50 48](https://user-images.githubusercontent.com/88108344/130335655-fc4762b1-2441-43c6-ab91-3f1b331eff00.png)

**Comment by Visnaa** [comment]
I've updated the deepslate onyx texture now so I think it doesn't look like deepslate coal anymore
![2021-08-30_12 04 16](https://user-images.githubusercontent.com/76943911/131323437-8fc7b98d-9a7a-4afc-8577-9f8ee8234c65.png)
