### ISSUE TITLE
Crash on Start (potentially a Forge issue)

### ISSUE THREAD

**Issue by TheDraconicAge** [Visnaa/MoreJewels#4]
**Crash Report:**
[crash-2021-08-15_13.53.11-fml.txt](https://github.com/Visnaa/MoreJewels/files/6988609/crash-2021-08-15_13.53.11-fml.txt)
**Latest.log**
[latest.log](https://github.com/Visnaa/MoreJewels/files/6988611/latest.log)

**Comment by Visnaa** [comment]
Hello,
Today I tried to fix all the issues you reported. If these issues no longer appear, please close all issue reports.
Thank you,
Visnaa
